### ISSUE TITLE
asciidoctor versioning different between Gem and lockfile

### ISSUE THREAD

**Issue by notapatch** [madeindjs/api_on_rails#10]
I'm not sure how important the move from 1.5 to 2.0 so I haven't put a pull request in. Before you can run the rake build the user has to fix this issue.

```
# Gemfile
gem 'asciidoctor', '~> 1.5'
```

```
# Gemfile.lock
asciidoctor (2.0.10)
```

**Comment by madeindjs** [comment]
Corrected by 0fcd4b2ea3f71c4cf0adc6874ff6e296ace77f11
