### ISSUE TITLE
Last link on Chapter 2 goes to the wrong code

### ISSUE THREAD

**Issue by notapatch** [madeindjs/api_on_rails#14]
The link on 'here'

> I’m not covering those in this book, since we are trying to learn how to actually implement this kind of functionality, but it is good to know though. By the way the code up to this point is **here**.

I believe this is the link:  https://github.com/madeindjs/market_place_api/commit/124873774b578af3df21136df5ee80f4d50da3bd

Confusing as it's rspec configuration when this book is covering minitest.

**Comment by madeindjs** [comment]
No this is because the project URL is https://github.com/madeindjs/market_place_api_6 . Did you found some bad link?

**Comment by notapatch** [comment]
Yes there is a bad link. The last link in Chapter 2 in "API on Rails 6" links to the market_place_api and not to market_place_api_6. However, I can't see which commit it should link to so I cannot put a pull request in. If you click "here" at the end of Chapter 2 you can see.

**Comment by madeindjs** [comment]
Corrected by 974321c68b1f0236ebc7b1d4fc5f90e56c589895
