### ISSUE TITLE
Chapter 3 - Build users - phrase 'user who will display a user'

### ISSUE THREAD

**Issue by notapatch** [madeindjs/api_on_rails#17]
Chapter 3

> Build users
> 
> It's time to make our first entry point. We will just start building the `show` action for the user who will display a user in JSON. We will first

Not sure what you mean: 

> user who will display a user in JSON.

**Comment by madeindjs** [comment]
It means who will build an entry point to show one user as JSON object: the `/api/v1/users/1` route.

**Comment by notapatch** [comment]
Added change into chapter 3 pull request

**Comment by madeindjs** [comment]
Thank you for the PR!
