### ISSUE TITLE
Chapter 4 - autoload_path

### ISSUE THREAD

**Issue by notapatch** [madeindjs/api_on_rails#19]
Chapter 4 autoload

```
Listing 5. lib/json_web_token.rb
# ...
module MarketPlaceApi
  class Application < Rails::Application
    # ...
    config.autoload_paths << Rails.root.join('lib')
  end
end
```

I notice you're using autoload. I find the area confusing. My understanding is  [autoloading lib was not threadsafe](https://github.com/rails/rails/issues/13142#issuecomment-275492070) which is a problem with Puma in production and the suggestion was you should stick lib into app :-|  I couldn't bring myself to do that and went with the other suggestion of changing autoload to eager load, which autoloads in development and eager loads, no requests until code loaded, in production.

https://stackoverflow.com/questions/19773266/confusing-about-autoload-paths-vs-eager-load-paths-in-rails-4?noredirect=1&lq=1

**Comment by madeindjs** [comment]
Thank you for this report. I was not aware about this problem. So you recommend to stick with a fixed `require` in file who need `JsonWebToken` lib?

Here an example with a controller

~~~ruby
# app/controllers/api/v1/tokens_controller.rb
require 'json_web_token'

class Api::V1::TokensController < ApplicationController
~~~

**Comment by notapatch** [comment]
It's been a while so I don't have the code here to test. I would make the smallest change that solved the problem. After this change Rails will eager load in production. This means constants will be loaded before accepting any requests. However, in development it will continue to autoload as before.

```
Listing 5. lib/json_web_token.rb
# ...
module MarketPlaceApi
  class Application < Rails::Application
    # ...  \/\/\/\/\/\/\/\/
    config.eager_load_paths << Rails.root.join('lib')
  end
end
```

Feel free to ask any questions if I haven't been clear.

### Further Reading
https://blog.bigbinary.com/2016/08/29/rails-5-disables-autoloading-after-booting-the-app-in-production.html

**Comment by madeindjs** [comment]
Thank for explanation. It's good to know. I just updated the book 5f9bd7d5dc222da9ae73e9e3ba806b5151cfb9de
