### ISSUE TITLE
Image to embed not found in chapter 02

### ISSUE THREAD

**Issue by franklinjosmell** [madeindjs/api_on_rails#30]
When I run "rake build:pdf[6,en]" for generate the pdf version. I get:

`asciidoctor: WARNING: image to embed not found or not readable: .../api_on_rails/rails6/en/img/img/data_model.png`

This happened after merge the pull request #24

**Comment by madeindjs** [comment]
Thanks for report, I will take a look.

**Comment by madeindjs** [comment]
Corrected by #31
