### ISSUE TITLE
@authentication = MockController.new OR @authentication = Authentication.new ?

### ISSUE THREAD

**Issue by tenzan** [madeindjs/api_on_rails#35]
Hi Alex,

In your PDF book, regarding `test/controllers/concerns/authenticable_test.rb`

on page 56 it is
`@authentication = MockController.new`

but on page 57, it is
`@authentication = Authentication.new`

Which one is correct?

Regards,
Askar

**Comment by bandithijo** [comment]
Hello @tenzan ,
You can referrer the code of the market_place_api project on here.
[github.com/madeindjs/market_place_api_6/blob/master/test/controllers/concerns/authenticable_test.rb](https://github.com/madeindjs/market_place_api_6/blob/master/test/controllers/concerns/authenticable_test.rb)

**Comment by tenzan** [comment]
Hi @bandithijo 

Thanks, I already checked that.
Just wanted to see author's comment, because this is might be something he should correct the ebook content.

**Comment by madeindjs** [comment]
Hello @tenzan , thanks to report this little mistake. I just corrected by the commit 4abff6f13325b77e58d14fc06f62e8f746236bbf . Please feel free to send a pull request for little fix like that .

Also thank you @bandithijo for your help on this issue ;)
