### ISSUE TITLE
Number of test assertions mentioned on the page 58

### ISSUE THREAD

**Issue by tenzan** [madeindjs/api_on_rails#36]
Hi Alex,

On the page 58 of the PDF, when running tests, you mentioned 19 assertions as per screenshot below.
But in my case, the number if 18.
https://github.com/tenzan/cms-rails-api/tree/3459ebbf5a8a8bf9c02e32e30e773cadd39696aa

<img width="670" alt="Screen Shot 2020-01-02 at 14 49 54" src="https://user-images.githubusercontent.com/227346/71653369-44604100-2d6f-11ea-9ee6-6f4d8aa0c44c.png">

Regards,
Askar

**Comment by madeindjs** [comment]
Thanks for report, I just commited a correction: 33d499ccdc3a09c2ef6d45c26e4b626d04e1e562
