### ISSUE TITLE
Rails 5.2 switched to credentials

### ISSUE THREAD

**Issue by Heroturtle** [madeindjs/api_on_rails#39]
Rails 5.2 replaced secrets with credentials. Chapter 4 still uses secrets which is not best practice anymore.

**Comment by Heroturtle** [comment]
Sorry, just found your example code in another repository which uses credentials. Maybe change the line:
SECRET_KEY = Rails.application.secrets.secret_key_base.to_s
in lib/json_web_token.rb
to something like Rails.application.credentials.dig(:secret.key_base).to_s
and change the introduction example password 'my_secret_key' to something like 'my_secret_credential'

**Comment by madeindjs** [comment]
Sorry for my late. Someone I think this per on `market_place_api` project implement your need : https://github.com/madeindjs/market_place_api_6/pull/12/files .

Currently I not updated book but feel free to make a PR if you think this will be needed.

**Comment by madeindjs** [comment]
I made [this fix](https://github.com/madeindjs/api_on_rails/commit/c86c63db341c25058e38e8b02184f0ea460a0cd6) so I think it's sufficient. What do you think about ?
