### ISSUE TITLE
How to access api in postman or browser ? 

### ISSUE THREAD

**Issue by theagilecoder** [madeindjs/api_on_rails#4]
Hi, i understand you using prax/pow but if i dont want to use them and instead try out the api on postman/browser using localhost:3000 , then what would be the URI/URL for that ? Thanks in advance.

**Comment by madeindjs** [comment]
Prax / Pow allow you to easily simulate a local subdomain. If you don't you want use them you can:

1. Add an alias in you `/etc/host`
2. Use <http://api.lvh.me:3000> which is an alias for <http://localhost:3000>
