### ISSUE TITLE
Consider updating fast_jsonapi to  jsonapi-serializer

### ISSUE THREAD

**Issue by benediktms** [madeindjs/api_on_rails#54]
The fast_jsonapi gem is no longer maintained by Netflix, as stated on the GitHub repo. Consider updating the content to reflect the [jsonapi-serializer](https://github.com/jsonapi-serializer/jsonapi-serializer) gem which is a community maintained fork.

**Comment by madeindjs** [comment]
Good to know, I was not aware about this. Thanks for report.

**Comment by promisepreston** [comment]
Hi @madeindjs, are you working on this at the moment, or can I help out with updating it?

**Comment by madeindjs** [comment]
Hi @promisepreston , I not working on this for the moment so you can make a PR if you want it. If you do so, don't forget to add you name in contributors ;)

**Comment by promisepreston** [comment]
I have opened some pull requests to addresses this.

**Comment by madeindjs** [comment]
Closed by #57 , thank you again @promisepreston
