### ISSUE TITLE
N+1 Queries fix is wrong - include should be include*s*

### ISSUE THREAD

**Issue by notapatch** [madeindjs/api_on_rails#61]
The fix in the code is incorrect it should be include_s_ and not include. I can't do a PR because I'm not sure how you want to fix it.

The wrong code is first introduced in Prevention of N + 1 requests. Listing 152. `app/controllers/api/v1/products_controller.rb`

```ruby
ApplicationController
  # ...
  def index
    @products = Product.includes(:user)
                       .page(current_page)
                       .per(per_page)
                       .search(params)

    options = get_links_serializer_options('api_v1_products_path', @products)
    # needs an s \/
    options[:include] = [:user]

    render json: ProductSerializer.new(@products, options).serializable_hash.to_json
  end
  # ...
end
```

The book code demonstrates that with the change in Listing 152 there is still an N+1 error in products.

```
GET /api/v1/products
USE eager loading detected
  Product => [:user]
  Add to your finder: :includes => [:user]
He even tells us how to correct it:
> Add to your search engine
includes ⇒ [: user]
```

Then there's a final listing 154 that copies the Listing 152, along with the mistake. 

I can't see a way of changing just the code. I think some writing must be changed as well.

**Comment by madeindjs** [comment]
Thre are two different includes:

1. `Product.includes(:user)` this one is from Active Record and it loads relations `Product#user`
2. `options[:include] = [:user]` this one is from [fast_jsonapi options](https://github.com/Netflix/fast_jsonapi#compound-document)

But it seem that [code example does not include `includes(:user)`](https://github.com/madeindjs/market_place_api_6/blob/a6f88370710e69f8aec9a059a1027e3b5ade8038/app/controllers/api/v1/products_controller.rb#L9). I added warning disappeared:

```
Started GET "/api/v1/products" for ::1 at 2021-01-24 08:57:41 +0100
   (0.1ms)  SELECT sqlite_version(*)
Processing by Api::V1::ProductsController#index as JSON
   (0.2ms)  SELECT COUNT(*) FROM "products"
  ↳ app/controllers/concerns/paginable.rb:9:in `get_links_serializer_options'
  Product Load (0.2ms)  SELECT "products".* FROM "products" LIMIT ? OFFSET ?  [["LIMIT", 20], ["OFFSET", 0]]
  ↳ app/controllers/api/v1/products_controller.rb:17:in `index'
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (?, ?, ?)  [["id", 7], ["id", 8], ["id", 9]]
  ↳ app/controllers/api/v1/products_controller.rb:17:in `index'
   (0.2ms)  SELECT "products"."id" FROM "products" WHERE "products"."user_id" = ?  [["user_id", 7]]
  ↳ app/controllers/api/v1/products_controller.rb:17:in `index'
   (0.1ms)  SELECT "products"."id" FROM "products" WHERE "products"."user_id" = ?  [["user_id", 8]]
  ↳ app/controllers/api/v1/products_controller.rb:17:in `index'
   (0.2ms)  SELECT "products"."id" FROM "products" WHERE "products"."user_id" = ?  [["user_id", 9]]
  ↳ app/controllers/api/v1/products_controller.rb:17:in `index'
Completed 200 OK in 50ms (Views: 2.4ms | ActiveRecord: 3.8ms | Allocations: 22119)
```

Can you try it and confirm that works?

**Comment by madeindjs** [comment]
Corrected with [this commit](https://github.com/madeindjs/market_place_api_6/commit/91c9992ed615d0ec3454bc9598f0f1bb60ae61d5).

**Comment by notapatch** [comment]
Yes, I got confused between the `include`  for the serialization and the `includes` for the N+1 query. 

On re-reading the section it now makes sense. Glad the code example is fixed as I would have checked my code against it when things didn't make sense.

Closing.
