### ISSUE TITLE
Failure during a rake test because of wrong password attribute in test/models/user_test.rb

### ISSUE THREAD

**Issue by avalou** [madeindjs/api_on_rails#68]
In the test/models/user_test.rb file, I think 
`test 'user with a valid email should be valid' do
  user = User.new(email: 'test@test.org', **password_digest**: 'test')
  assert user.valid?
end`

should rather be :

`test 'user with a valid email should be valid' do
  user = User.new(email: 'test@test.org', **password**: 'test')
  assert user.valid?
end`

In my case it caused a failure during a `rake test`.

**Comment by madeindjs** [comment]
Corrected by #66 . But for me tests passed with both:

- `User.new(email: 'test@test.org', password: 'test')`
- `User.new(email: 'test@test.org', password_digest: 'test')`
