### ISSUE TITLE
Chapter 2 API Versioning

### ISSUE THREAD

**Issue by notapatch** [madeindjs/api_on_rails#9]
Hi madeindjs

Thanks for looking at this book there are very little covering Rails APIs. I couldn't work out this bit on Chapter 2:  

> ### Api versioning
> At this point we should have a nice routes mapping using a namespace. Your routes.rb file should look like this:
> 
> Listing 5. config/routes.rb
> ```
> Rails.application.routes.draw do
>   # Api definition
>   namespace :api, defaults: { format: :json }, path: '/'  do     <=== ?
>     # We are going to list our resources here
>   end
> end
> ```

The only problem is that the `path: '/'` has just appeared after the final commit and it's not clear where it came from as it was not in any of the previous listings.

**Comment by madeindjs** [comment]
In fact the `path` option is not mandatory but you right I will correct it. Thank you for report.

**Comment by madeindjs** [comment]
Corrected by 2bd37d2532e3a8d8e22ca9a506e96b7948114541
